// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy7mEvVfHDELEPCk706whe7NsXrNtFE0g',
    appId: '1:703980877035:web:9047d154ff834ffaecbaae',
    messagingSenderId: '703980877035',
    projectId: 'fluttercrud-f5591',
    authDomain: 'fluttercrud-f5591.firebaseapp.com',
    storageBucket: 'fluttercrud-f5591.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA9ZXYs2_vuGkQgFRWUbjeby7rdir4Nk0',
    appId: '1:703980877035:android:092df6312f0074b1ecbaae',
    messagingSenderId: '703980877035',
    projectId: 'fluttercrud-f5591',
    storageBucket: 'fluttercrud-f5591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyL6uPFkUKSC2ET07wX1nGI3z7UmyEJL8',
    appId: '1:703980877035:ios:36fe6ae1760a7606ecbaae',
    messagingSenderId: '703980877035',
    projectId: 'fluttercrud-f5591',
    storageBucket: 'fluttercrud-f5591.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyL6uPFkUKSC2ET07wX1nGI3z7UmyEJL8',
    appId: '1:703980877035:ios:36fe6ae1760a7606ecbaae',
    messagingSenderId: '703980877035',
    projectId: 'fluttercrud-f5591',
    storageBucket: 'fluttercrud-f5591.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy7mEvVfHDELEPCk706whe7NsXrNtFE0g',
    appId: '1:703980877035:web:3d82b23311c94a9cecbaae',
    messagingSenderId: '703980877035',
    projectId: 'fluttercrud-f5591',
    authDomain: 'fluttercrud-f5591.firebaseapp.com',
    storageBucket: 'fluttercrud-f5591.appspot.com',
  );
}
